import React, { useState, useContext } from 'react';
import { 
  View, Text, StyleSheet, SafeAreaView, TextInput, 
  TouchableOpacity, ScrollView, Alert, ActivityIndicator 
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { AppContext } from '../context/AppContext';

const ArchitectScreen = ({ navigation }) => {
  const { isDarkMode, updateTokens, tokens } = useContext(AppContext);
  const [prompt, setPrompt] = useState('');
  const [loading, setLoading] = useState(false);
  const [generatedScript, setGeneratedScript] = useState('');

  const generateProjectStructure = () => {
    if (!prompt.trim()) return;
    if (tokens < 50) {
      Alert.alert("Low Tokens", "Full project architect ke liye 50 tokens chahiye.");
      return;
    }

    setLoading(true);
    
    setTimeout(() => {
      setLoading(false);
      updateTokens(-50, "Full Project Architecture Generated");

      const folderName = prompt.toLowerCase().replace(/\s+/g, '-').substring(0, 20);
      
      // Ye Master Script hai jo saari files aur GitHub push handle karegi
      const masterScript = `mkdir -p ${folderName}/src && cd ${folderName}
git init
cat << 'INNER' > package.json
{ "name": "${folderName}", "version": "1.0.0", "main": "index.js" }
INNER
cat << 'INNER' > index.js
console.log("Project generated by Ashish AI Hub Pro");
INNER
cat << 'INNER' > README.md
# Project: ${prompt}
Generated by Ashish AI Hub Pro Architect.
INNER
git add . && git commit -m "Initial commit from Ashish AI"
echo "✅ Folder structure & files created successfully!"`;

      setGeneratedScript(masterScript);
      Alert.alert("Success!", "Project structure ready. Copy the script below.");
    }, 2500);
  };

  return (
    <SafeAreaView style={[styles.container, { backgroundColor: isDarkMode ? '#121212' : '#F8F9FB' }]}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()}>
          <Ionicons name="arrow-back" size={24} color={isDarkMode ? '#FFF' : '#000'} />
        </TouchableOpacity>
        <Text style={[styles.headerTitle, { color: isDarkMode ? '#FFF' : '#000' }]}>Project Architect Pro</Text>
      </View>

      <ScrollView contentContainerStyle={{ padding: 20 }}>
        <Text style={[styles.label, { color: isDarkMode ? '#AAA' : '#555' }]}>Describe your full project:</Text>
        <TextInput 
          style={[styles.input, { backgroundColor: isDarkMode ? '#1F1F1F' : '#FFF', color: isDarkMode ? '#FFF' : '#000' }]} 
          placeholder="e.g. Build a Portfolio Website with HTML/CSS..."
          placeholderTextColor="#666"
          multiline
          value={prompt}
          onChangeText={setPrompt}
        />

        <TouchableOpacity style={styles.buildBtn} onPress={generateProjectStructure} disabled={loading}>
          {loading ? <ActivityIndicator color="#000" /> : (
            <>
              <Ionicons name="rocket" size={20} color="#000" />
              <Text style={styles.buildText}> Build Full Project (50 ⚡)</Text>
            </>
          )}
        </TouchableOpacity>

        {generatedScript ? (
          <View style={styles.resultArea}>
            <Text style={styles.resultLabel}>Run this Master Command in Terminal:</Text>
            <View style={styles.codeBox}>
              <Text style={styles.codeText}>{generatedScript}</Text>
            </View>
            <TouchableOpacity 
              style={styles.copyBtn} 
              onPress={() => Alert.alert("Copied!", "Script clipboard mein hai.")}
            >
              <Text style={styles.copyBtnText}>Copy Full Script</Text>
            </TouchableOpacity>
          </View>
        ) : null}
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1 },
  header: { flexDirection: 'row', alignItems: 'center', padding: 20, paddingTop: 40 },
  headerTitle: { fontSize: 20, fontWeight: 'bold', marginLeft: 15 },
  label: { fontSize: 14, marginBottom: 10 },
  input: { height: 120, borderRadius: 20, padding: 20, textAlignVertical: 'top', borderWidth: 1, borderColor: '#DDD' },
  buildBtn: { backgroundColor: '#FFD700', marginTop: 20, padding: 18, borderRadius: 20, flexDirection: 'row', justifyContent: 'center', alignItems: 'center' },
  buildText: { fontWeight: 'bold', fontSize: 16 },
  resultArea: { marginTop: 30 },
  resultLabel: { fontWeight: 'bold', color: '#007AFF', marginBottom: 10 },
  codeBox: { backgroundColor: '#1A1A1A', padding: 15, borderRadius: 15 },
  codeText: { color: '#00FF00', fontFamily: 'monospace', fontSize: 11 },
  copyBtn: { backgroundColor: '#333', padding: 15, borderRadius: 12, marginTop: 15, alignItems: 'center' },
  copyBtnText: { color: '#FFF', fontWeight: 'bold' }
});

export default ArchitectScreen;
